-- Generated by scripts/cms-seed-sql.mts from src/cms/documents.ts — do not edit by hand.
-- Loads the site's original copy into the CMS. Existing documents are left untouched.

insert into public.cms_documents (id, data)
values ('site', $cms${
  "brand": {
    "name": "NAMBIRAJ",
    "tagline": "LAW DYNASTY",
    "logo": "/logo.png"
  },
  "seo": {
    "title": "Nambiraj Law Dynasty — Justice is our lineage",
    "description": "Continuing the legacy of Mr. C. Nambiraj — timeless ethical values with modern legal infrastructure."
  },
  "nav": [
    {
      "label": "Home",
      "href": "/",
      "children": []
    },
    {
      "label": "The Firm",
      "href": "/about",
      "children": [
        {
          "label": "Firm History",
          "href": "/about#firm-history"
        },
        {
          "label": "About Us",
          "href": "/about#about-us"
        }
      ]
    },
    {
      "label": "Practicing Area",
      "href": "/practicing-area",
      "children": []
    },
    {
      "label": "Services",
      "href": "/services",
      "children": []
    },
    {
      "label": "Our Team",
      "href": "/our-team",
      "children": []
    },
    {
      "label": "News",
      "href": "/news",
      "children": []
    },
    {
      "label": "Contact Us",
      "href": "/contact",
      "children": []
    }
  ],
  "contact": {
    "address": "Nambiraj Law Dynasty LLP.,\nH-14, T.N.H.B. Colony, 2nd Phase,\nKrishnagiri - 635 002",
    "email": "nambirajlawdynasty@gmail.com",
    "phones": [
      {
        "display": "+91 63695 04141",
        "number": "+916369504141"
      },
      {
        "display": "04343 225164",
        "number": "+914343225164"
      }
    ],
    "whatsappNumber": "916369504141",
    "whatsappMessage": "Hello, I would like to inquire about your legal services.",
    "hours": "Mon — Sat · 9 AM to 6 PM"
  },
  "social": [
    {
      "platform": "instagram",
      "url": "https://www.instagram.com/nambirajlawdynasty"
    },
    {
      "platform": "facebook",
      "url": "https://www.facebook.com/share/1KD26bRhzb/"
    },
    {
      "platform": "linkedin",
      "url": "https://www.linkedin.com/in/nambiraj-law-dynasty-8251a0417"
    }
  ],
  "footer": {
    "about": "Continuing a 55-year legacy of legal excellence. Dedicated to the vision of Mr. C. Nambiraj.",
    "exploreHeading": "Explore",
    "officeHeading": "Office",
    "copyright": "© 2026 Nambiraj Law Dynasty LLP. All rights reserved."
  }
}$cms$::jsonb)
on conflict (id) do nothing;

insert into public.cms_documents (id, data)
values ('home', $cms${
  "seo": {
    "title": "Nambiraj Law Dynasty — Justice is our lineage",
    "description": "Continuing the legacy of Mr. C. Nambiraj — timeless ethical values with modern legal infrastructure."
  },
  "hero": {
    "image": "/hero-library.jpg",
    "badge": "Since 1969",
    "title": "Justice is not just a profession",
    "subtitle": "it is our lineage.",
    "lead": "Continuing the legacy of Mr. C. Nambiraj, we blend timeless ethical values with modern legal infrastructure to serve the under-privileged and the visionary alike."
  },
  "founder": {
    "image": "/nambiraj.jpg",
    "imageAlt": "Mr. C. Nambiraj",
    "statNumber": "55",
    "statSuffix": "+",
    "statLabel": "Years of\nPractice",
    "statSince": "Since 1969",
    "heading": "The Phenomenon of\nMr. C. Nambiraj",
    "intro": "He was more than a lawyer; he was an intellectual legend who entered practice in 1969 and focused on the welfare of the under-privileged with absolute grace and humility.",
    "quote": "A good lawyer throws himself on your part so heartily, that makes him win in all situations.",
    "closing": "Today, N. Sureka leads a team of talented legal professionals, guiding the dynasty with the same principles of ethical practice and resourcefulness."
  },
  "areas": {
    "eyebrow": "Expertise",
    "heading": "Practicing Areas",
    "linkLabel": "View All Domains",
    "items": [
      {
        "icon": "section",
        "name": "Civil Litigation",
        "blurb": "Defending rights and resolving disputes with the same tenacity that built our dynasty."
      },
      {
        "icon": "courthouse",
        "name": "Governmental Affairs",
        "blurb": "Navigating complex regulatory landscapes with decades of institutional knowledge."
      },
      {
        "icon": "scales",
        "name": "Business Law",
        "blurb": "Practical knowledge and legal foresight for modern enterprises and startups alike."
      }
    ]
  },
  "environment": {
    "heading": "A Modern Learning Environment",
    "body": "We invest in technology and infrastructure to collaborate effectively while maintaining the highest standards of publication and research.",
    "bullets": [
      "Holistic Frameworks",
      "Mentoring Relationships",
      "Exclusive Legal Resources"
    ],
    "image": "/modern-office.jpg",
    "imageAlt": "Modern office"
  }
}$cms$::jsonb)
on conflict (id) do nothing;

insert into public.cms_documents (id, data)
values ('about', $cms${
  "seo": {
    "title": "About Us — Nambiraj Law Dynasty",
    "description": "The phenomenon of Mr. C. Nambiraj — 55+ years of legal practice, continued today as the Nambiraj Law Dynasty."
  },
  "hero": {
    "eyebrow": "Our Firm",
    "title": "About Nambiraj Law Dynasty",
    "statNumber": "55+",
    "statLabel": "Years of Legal Practice · Since 1969"
  },
  "history": {
    "heading": "Firm History",
    "body": "A good lawyer is not the man who has an eye to every side and angle of contingency, but who throws himself on your part so heartily that it makes him win in all situations. Mr. C. Nambiraj was such a legend — intellectual, smart, learned, cultured, resourceful, wise, modest, demure and exemplary.\n\nHe fought for the rights of his clients, focusing on the welfare of the people exceptionally and principally for the under-privileged. He was honest and dedicated to his profession, and maintained an ethical practice throughout his lifetime with cordial relationships with his clients.\n\nHe used his talents to the fullest, for all the right purposes — by living for what he believed in, by working very hard, respecting the people he worked with, and living with absolute grace and humility. These are the old fashioned, timeless values that made this man a phenomenon. He earned name, fame and men."
  },
  "aboutUs": {
    "heading": "About Us",
    "body": "Mr. C. Nambiraj, the founder of this dynasty, began his practice in 1969. After his demise in 2008, the office was succeeded by his daughter **N. Sureka**, who has developed it into a team of talented legal professionals — guided by the principles of C. Nambiraj as *“Nambiraj Law Dynasty”*.\n\nWe offer diverse legal, business and governmental backgrounds, bringing vast experience and practical knowledge to each client we represent. The firm prides itself on its commitment to knowing the law and encouraging its professionals to be at the forefront of the latest legal developments.\n\nThe firm has built a learning environment, rich with mentoring relationships and knowledge sharing through invaluable publications, holistic frameworks and access to the most exclusive resources. We invest in technology and infrastructure that allows our professionals and clients to work more efficiently, collaborate effectively and maintain standards."
  }
}$cms$::jsonb)
on conflict (id) do nothing;

insert into public.cms_documents (id, data)
values ('practice-areas', $cms${
  "seo": {
    "title": "Practicing Areas — Nambiraj Law Dynasty",
    "description": "Nine domains of practice supported by a team of talented professionals and decades of institutional memory."
  },
  "hero": {
    "eyebrow": "Expertise",
    "title": "Practicing Areas",
    "lead": "Nine domains of practice supported by a team of talented professionals and decades of institutional memory."
  },
  "areas": [
    {
      "name": "Civil Litigation",
      "blurb": "Comprehensive representation in civil disputes — contracts, property, commercial and personal matters."
    },
    {
      "name": "Criminal Defense",
      "blurb": "Rigorous defense strategies in trial and appellate courts protecting constitutional rights."
    },
    {
      "name": "Family Law",
      "blurb": "Discreet, compassionate counsel for matrimonial, succession, custody and maintenance matters."
    },
    {
      "name": "Corporate & Business Law",
      "blurb": "Advising businesses on governance, compliance, contracts and regulatory frameworks."
    },
    {
      "name": "Property & Real Estate",
      "blurb": "Title verification, land disputes, conveyancing and registration."
    },
    {
      "name": "Constitutional Law",
      "blurb": "Writ petitions, fundamental rights and public interest litigation."
    },
    {
      "name": "Governmental Affairs",
      "blurb": "Navigating regulatory frameworks with deep institutional knowledge."
    },
    {
      "name": "Arbitration & Mediation",
      "blurb": "Out-of-court dispute resolution with practical commercial sense."
    },
    {
      "name": "Taxation & Revenue",
      "blurb": "Direct and indirect tax disputes, advisory and assessments."
    }
  ]
}$cms$::jsonb)
on conflict (id) do nothing;

insert into public.cms_documents (id, data)
values ('services', $cms${
  "seo": {
    "title": "Services — Nambiraj Law Dynasty",
    "description": "A full spectrum of legal services — from courtroom advocacy to quiet, careful drafting — delivered with the ethical rigor that has defined our practice since 1969."
  },
  "hero": {
    "eyebrow": "What We Do",
    "title": "Services",
    "lead": "A full spectrum of legal services — from courtroom advocacy to quiet, careful drafting — delivered with the ethical rigor that has defined our practice since 1969."
  },
  "groups": [
    {
      "title": "Litigation & Dispute Resolution",
      "description": "Representation and advocacy across trial courts and the High Court, with thorough case preparation at every stage.",
      "items": [
        {
          "name": "Trial Court Representation",
          "blurb": "Conducting civil, criminal and family matters before district and metropolitan courts with thorough preparation of pleadings and evidence."
        },
        {
          "name": "High Court Practice",
          "blurb": "Drafting and arguing writs, appeals and revisions before the High Court with rigorous case preparation."
        },
        {
          "name": "Arbitration & Mediation",
          "blurb": "Cost-effective resolution of commercial and civil disputes through institutional and ad-hoc arbitration, conciliation and mediation."
        }
      ]
    },
    {
      "title": "Advisory & Counseling",
      "description": "Strategic legal counsel for individuals, families and enterprises facing complex or recurring legal questions.",
      "items": [
        {
          "name": "Strategic Legal Opinions",
          "blurb": "Reasoned written opinions on contentious points of law, regulatory exposure and litigation risk."
        },
        {
          "name": "Retainer Advisory",
          "blurb": "Ongoing counsel for businesses and HNIs covering day-to-day legal queries, compliance and risk reviews."
        },
        {
          "name": "Pre-Litigation Strategy",
          "blurb": "Notice drafting, negotiation and settlement structuring to resolve matters before they reach the courtroom."
        }
      ]
    },
    {
      "title": "Drafting & Documentation",
      "description": "Precision drafting of contracts, deeds and personal instruments — clear, enforceable and tailored to intent.",
      "items": [
        {
          "name": "Contracts & Agreements",
          "blurb": "Commercial contracts, service agreements, NDAs, leases, MoUs and shareholder arrangements."
        },
        {
          "name": "Conveyancing & Title Deeds",
          "blurb": "Sale deeds, gift deeds, partition deeds, mortgages and releases drafted with full title verification."
        },
        {
          "name": "Wills, Trusts & Succession",
          "blurb": "Confidential preparation of wills, family settlements, trust deeds and succession planning instruments."
        }
      ]
    },
    {
      "title": "Property & Real Estate",
      "description": "End-to-end property practice — from due diligence through registration and dispute defence.",
      "items": [
        {
          "name": "Title Search & Due Diligence",
          "blurb": "Verification of ownership, encumbrances and statutory clearances before purchase or financing."
        },
        {
          "name": "Land & Property Disputes",
          "blurb": "Recovery of possession, specific performance, partition suits and boundary disputes."
        },
        {
          "name": "Registration & Mutation",
          "blurb": "Coordination of registration, stamp duty and revenue mutation across applicable authorities."
        }
      ]
    },
    {
      "title": "Corporate, Tax & Regulatory",
      "description": "Practical counsel for businesses navigating compliance, structuring and regulatory engagement.",
      "items": [
        {
          "name": "Corporate Compliance",
          "blurb": "Companies Act, FEMA, labour and sectoral compliance — periodic filings, registers and audit support."
        },
        {
          "name": "Taxation & Revenue Disputes",
          "blurb": "Representation in income tax, GST, customs and stamp duty proceedings, including appellate forums."
        },
        {
          "name": "Regulatory Liaison",
          "blurb": "Engagement with statutory authorities, licensing bodies and tribunals on behalf of clients."
        }
      ]
    },
    {
      "title": "Registrations & Statutory Filings",
      "description": "End-to-end assistance with statutory registrations and identity instruments required to start, run and formalise a business.",
      "items": [
        {
          "name": "GST Registration & Filings",
          "blurb": "New GST registration, monthly and annual return filings, amendments, cancellations and representation in GST proceedings."
        },
        {
          "name": "FSSAI Food Licence",
          "blurb": "Basic, State and Central FSSAI registrations and renewals for food businesses, traders, manufacturers and cloud kitchens."
        },
        {
          "name": "Company & LLP Registration",
          "blurb": "Incorporation of Private Limited Companies, LLPs, OPCs and partnership firms, including MoA/AoA drafting and post-incorporation compliance."
        },
        {
          "name": "Digital Signature Certificate (DSC)",
          "blurb": "Issuance and renewal of Class 3 Digital Signature Certificates for individuals, directors and authorised signatories."
        },
        {
          "name": "PAN & TAN Applications",
          "blurb": "Fresh PAN and TAN applications, corrections, reprints and linkage with statutory records for individuals and entities."
        }
      ]
    },
    {
      "title": "Notarial & Allied Services",
      "description": "Practical, day-to-day legal services that support both individuals and ongoing client matters.",
      "items": [
        {
          "name": "Notarisation & Attestation",
          "blurb": "Affidavits, declarations, indemnities, power of attorney and document attestations."
        },
        {
          "name": "Court & Document Filing",
          "blurb": "Filing, certified copy applications and procedural follow-ups across courts and registries."
        },
        {
          "name": "Legal Audits & Research",
          "blurb": "Bespoke legal research, case-law studies and internal legal audits for institutional clients."
        }
      ]
    }
  ]
}$cms$::jsonb)
on conflict (id) do nothing;

insert into public.cms_documents (id, data)
values ('team', $cms${
  "seo": {
    "title": "Our Team — Nambiraj Law Dynasty",
    "description": "The advocates and counsel who carry the Nambiraj Law Dynasty forward — specialists across litigation, corporate, property and advisory practice."
  },
  "hero": {
    "eyebrow": "The People",
    "title": "Our Team",
    "lead": "The advocates and counsel who carry the Nambiraj Law Dynasty forward — each a specialist, all held to the same standard of diligence and discretion."
  },
  "founder": {
    "photo": "/team/c-nambiraj.jpg",
    "name": "Mr. C. Nambiraj",
    "role": "Founder · Senior Advocate"
  },
  "members": [
    {
      "name": "N. Sureka",
      "initials": "NS",
      "role": "Partner · Senior Advocate",
      "bio": "Successor to the dynasty's founder. Trial and appellate advocacy across civil, commercial and family matters, with a record of hard-fought, thoroughly prepared cases.",
      "focus": [
        "Litigation",
        "Family"
      ],
      "photo": "/team/n-sureka.jpg"
    },
    {
      "name": "Nagendhran. S",
      "initials": "NG",
      "role": "Managing Partner · Administration",
      "bio": "The visionary behind the Nambiraj Law Dynasty platform, committed to blending law, technology and professional excellence. Inspired by the legacy of Senior Advocate C. Nambiraj.",
      "focus": [
        "Administration",
        "Technology"
      ],
      "photo": "/team/nagendhran-s.jpg"
    },
    {
      "name": "L. Pachappan",
      "initials": "LP",
      "role": "Senior Associate · Criminal Defence",
      "bio": "Disciple of C. Nambiraj. Defence strategy and bail-to-trial representation, with a steady focus on protecting constitutional rights.",
      "focus": [
        "Criminal",
        "Bail"
      ],
      "photo": "/team/l-pachappan.jpg"
    },
    {
      "name": "Sanjay Balamurugaen",
      "initials": "SB",
      "role": "Associate Advocate · Real Estate",
      "bio": "Handling civil matters and real estate — end-to-end property disputes.",
      "focus": [
        "Real Estate",
        "Civil"
      ],
      "photo": "/team/sanjay-balamurugaen.jpg"
    },
    {
      "name": "Syed Safeer Ahmed",
      "initials": "SA",
      "role": "Senior Advocate Clerk",
      "bio": "Handling all clerical work for the chambers.",
      "focus": [
        "Clerical"
      ],
      "photo": "/team/syed-safeer-ahmed.jpg"
    },
    {
      "name": "G. Pradeepa",
      "initials": "GP",
      "role": "Junior Associate · Criminal",
      "bio": "Assisting on criminal matters from bail to trial.",
      "focus": [
        "Criminal",
        "Trial"
      ],
      "photo": "/team/g-pradeepa.jpg"
    },
    {
      "name": "N. Balaji",
      "initials": "NB",
      "role": "Junior Associate · Civil",
      "bio": "Civil, Criminal, Bail, Return of Property and Relaxation",
      "focus": [
        "Civil",
        "Criminal",
        "Bail",
        "Return of Property",
        "Relaxation"
      ],
      "photo": "/team/n-balaji.jpg"
    },
    {
      "name": "S. Tharani Shree",
      "initials": "TS",
      "role": "Junior Advocate · Civil",
      "bio": "",
      "focus": [
        "Civil"
      ],
      "photo": "/team/s-tharani-shree.jpg"
    },
    {
      "name": "S. Saranya",
      "initials": "SS",
      "role": "Junior Advocate · Civil",
      "bio": "",
      "focus": [
        "Civil"
      ],
      "photo": "/team/s-saranya.jpg"
    },
    {
      "name": "K. Kalaimathi",
      "initials": "KK",
      "role": "Junior Advocate · Family",
      "bio": "",
      "focus": [
        "Family"
      ],
      "photo": "/team/k-kalaimathi.jpg"
    },
    {
      "name": "S. Abinaya",
      "initials": "AB",
      "role": "Junior Advocate · Civil & Criminal",
      "bio": "",
      "focus": [
        "Civil",
        "Criminal"
      ],
      "photo": "/team/s-abinaya.jpg"
    },
    {
      "name": "A. Kannadhasan",
      "initials": "AK",
      "role": "",
      "bio": "",
      "focus": [],
      "photo": "/team/a-kannadhasan.jpg"
    },
    {
      "name": "V. Cecilia Abigail",
      "initials": "CA",
      "role": "",
      "bio": "",
      "focus": [],
      "photo": "/team/v-cecilia-abigail.jpg"
    }
  ]
}$cms$::jsonb)
on conflict (id) do nothing;

insert into public.cms_documents (id, data)
values ('news-page', $cms${
  "seo": {
    "title": "News — Nambiraj Law Dynasty",
    "description": "Updates, announcements and legal insights from the Nambiraj Law Dynasty."
  },
  "hero": {
    "eyebrow": "From the Chambers",
    "title": "News",
    "lead": "Updates, announcements and legal insights from the Nambiraj Law Dynasty."
  },
  "readMoreLabel": "Read more",
  "emptyMessage": "There are no news posts yet — please check back soon.",
  "backLabel": "All news"
}$cms$::jsonb)
on conflict (id) do nothing;

insert into public.cms_documents (id, data)
values ('contact', $cms${
  "seo": {
    "title": "Contact Us — Nambiraj Law Dynasty",
    "description": "Reach Nambiraj Law Dynasty in Krishnagiri — office address, phone, email and WhatsApp, or send an inquiry."
  },
  "hero": {
    "eyebrow": "Get in Touch",
    "title": "Contact Us",
    "lead": ""
  },
  "officeHeading": "Office",
  "whatsappLinkLabel": "Chat with us on WhatsApp",
  "showWhatsappButton": true,
  "form": {
    "inquiryTypes": [
      "Civil Matter",
      "Criminal Matter",
      "Property Dispute",
      "Corporate Advisory",
      "Family Law",
      "Other"
    ],
    "submitLabel": "Submit Inquiry",
    "successMessage": "Thank you — your enquiry has reached the chambers. We’ll be in touch shortly."
  }
}$cms$::jsonb)
on conflict (id) do nothing;

insert into public.cms_documents (id, data)
values ('disclaimer', $cms${
  "enabled": true,
  "title": "DISCLAIMER",
  "intro": "The rules of the Bar Council of India prohibit law firms from soliciting work or advertising in any manner. By clicking on ‘I AGREE’, the user acknowledges that:",
  "bullets": [
    "The user wishes to gain more information about Legalezi, its practice areas and its attorneys, for his/her own information and use;",
    "The information is made available/provided to the user only on his/her specific request and any information obtained or material downloaded from this website is completely at the user’s volition and any transmission, receipt or use of this site is not intended to, and will not, create any lawyer-client relationship; and",
    "None of the information contained on the website is in the nature of a legal opinion or otherwise amounts to any legal advice."
  ],
  "closing": "Legalezi is not liable for any consequence of any action taken by the user relying on material/information provided under this website. In cases where the user has any legal issues, he/she in all cases must seek independent legal advice.",
  "heading2": "Disclaimer & Confirmation",
  "intro2": "As per the rules of the Bar Council of India, we are not permitted to solicit work and advertise. By clicking on the “I AGREE” button below, you acknowledge the following:",
  "bullets2": [
    "there has been no advertisement, personal communication, solicitation, invitation or inducement of any sort whatsoever from us or any of our members to solicit any work through this website;",
    "you wish to gain more information about us for your own information and use;",
    "the information about us is provided to you on your specific request and any information obtained or materials downloaded from this website is completely at your own volition and any transmission, receipt or use of this site does not create any lawyer-client relationship; and that",
    "we are not liable for any consequence of any action taken by you relying on the material / information provided on this website."
  ],
  "closing2": "If you have any legal issues, you, in all cases, must seek independent legal advice.",
  "cookieNote": "We use cookies to enhance your experience. By continuing to visit this website you agree to our use of cookies.",
  "agreeLabel": "I Agree",
  "disagreeLabel": "I Disagree",
  "declineUrl": "https://www.google.com"
}$cms$::jsonb)
on conflict (id) do nothing;
