// Generates supabase/seed.sql from the default content in src/cms/documents.ts,
// so the database starts out with exactly the copy the site already shows.
//
//   npm run cms:seed-sql
//
// Runs under Node's built-in TypeScript type stripping (Node 22.18+ / 24).
// The seed only inserts documents that don't exist yet — re-running it never
// overwrites anything an editor has changed.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { DOCUMENTS } from "../src/cms/documents.ts";

const out = fileURLToPath(new URL("../supabase/seed.sql", import.meta.url));

const rows = Object.entries(DOCUMENTS).map(([id, doc]) => {
  const json = JSON.stringify(doc.defaults, null, 2);
  if (json.includes("$cms$")) throw new Error(`Document "${id}" contains the SQL quote tag $cms$`);
  return `insert into public.cms_documents (id, data)\nvalues ('${id}', $cms$${json}$cms$::jsonb)\non conflict (id) do nothing;`;
});

const sql = `-- Generated by scripts/cms-seed-sql.mts from src/cms/documents.ts — do not edit by hand.
-- Loads the site's original copy into the CMS. Existing documents are left untouched.

${rows.join("\n\n")}
`;

writeFileSync(out, sql);
console.log(`Wrote ${rows.length} documents to ${out}`);
